name: "Ubuntu-Test"
on:
  workflow_dispatch:
    # 手动触发

jobs:
  package:
    strategy:
      matrix: # 2022版本的Windows 即Win11 sqlite3数据写入会有闪退问题
        platform: [ubuntu-latest]
        go-version: [1.19.2]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: install MinGW
        if: matrix.platform == 'ubuntu-latest'
        run: apt install -y libx11-dev xvfb
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      - name: Build Wails app
        run: |
          wails build
      - name: upload artifacts ubuntu
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: GTools-linux-amd64
          path: build/bin/*
